"""Create all tables

Revision ID: d2940f0e3767
Revises: acc2309d38b1
Create Date: 2024-11-19 07:18:23.751200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2940f0e3767'
down_revision: Union[str, None] = 'acc2309d38b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('owner_name', sa.String(), nullable=True))
    op.drop_constraint('deliveries_owner_id_fkey', 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'users', ['owner_name'], ['id'])
    op.drop_column('deliveries', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key('deliveries_owner_id_fkey', 'deliveries', 'users', ['owner_id'], ['id'])
    op.drop_column('deliveries', 'owner_name')
    # ### end Alembic commands ###
